spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse1?serverTimezone=CET&createDatabaseIfNotExist=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080